### ISSUE TITLE
Incorrect docs for waitForImages

### ISSUE THREAD

**Issue by lostinpatterns** [anmarcek/jpictura#1]
The code appears to be querying the data attributes for the image's natural height and width on the `.item` element wrapping the `<img />` element, but in the docs for the waitForImages option, those data attributes appear on the `<img />` element.

I'd submit a pull request, but I'm not sure if you intended to do it how it's specified in the docs or in the code.

**Comment by anmarcek** [comment]
Dear @lostinpatterns ,

well spotted. Thank you for reporting the issue. I have already updated the docs (you were right, the docs are incorrect, not the code) and will push the change together with a few other things soon (in a few days).

Best regards,
Anton

**Comment by lostinpatterns** [comment]
Great, thanks! Very useful library.

**Comment by anmarcek** [comment]
The docs have been updated.
