### ISSUE TITLE
Responsiveness not that great on iPad and iPhone 6 Plus

### ISSUE THREAD

**Issue by siudocode** [anmarcek/jpictura#6]
This looks great on desktop and portrait smartphone in general, but the spacing is weird on iPad (portrait and horizontal) and iPhone 6Plus

![screen shot 2016-07-30 at 9 19 12 pm](https://cloud.githubusercontent.com/assets/11896191/17274043/777eaee0-569b-11e6-97e8-ff51c7d6d074.png)
![screen shot 2016-07-30 at 9 20 18 pm](https://cloud.githubusercontent.com/assets/11896191/17274044/77801c1c-569b-11e6-94e7-dadc8bb62479.png)

**Comment by anmarcek** [comment]
Dear @siuangie91 ,

thank you for your feedback. I will have a look at the issue. Which version if jPictura have you used? A few issues were fixed in the latest version (1.2) released just a few days ago.

Best regards,
Anton

**Comment by siudocode** [comment]
Hey Anton, 

Thanks for checking this out! I believed I used the most recent one (I installed using npm).

Angie

**Comment by anmarcek** [comment]
Hello,

sorry for late response. Seems like this issue is not related only to Apple devices. I have noticed a strange behavior in Chrome on Windows as well.

Anton

**Comment by anmarcek** [comment]
#7

**Comment by anmarcek** [comment]
Hello again,

I believe this issue is related to the more general issue #7 , which has been fixed in the newest version (1.2.3). Could you please update jPictura to the last version (1.2.3) and see if the fix helped? Thank you in advance.

Anton

**Comment by anmarcek** [comment]
Dear Angie,

I have already tested the fixed version (1.2.3) on both iPad and iPhone SE. Seems like everything is working fine now (a working example: https://jsfiddle.net/paf7g91p/). Please, download the latest version or update via npm. I am closing this issue now, however feel free to let me know again if anything goes wrong.

Anton
